'''
Created on Mar 20, 2014

@author: dgrewal
'''

import argparse

parser = argparse.ArgumentParser(prog='''Convert Museq vcf to counts''',
                                 description = '''Generates the tumour_counts from vcf generated by titan_preprocess component
                                                 of MutationSeq''')

parser.add_argument("-i","--infile", 
                    required = True, 
                    help= '''The vcf files generated by museq''')

parser.add_argument("-o","--outfile", 
                    required = True, 
                    help="The path to the counts file")

args,unknown = parser.parse_known_args()

